version: "3"

services:
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    restart: "no"
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: hadoop-master:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - my_custom_network
      - hadoop_network
    volumes:
      #- kafka_data:/usr/share/kafka/data
      - ./data:/usr/share/kafka/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - my_custom_network
      - hadoop_network
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    ports:
      - 5044:5044
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - my_custom_network
      - hadoop_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    hostname: kibana
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my_custom_network
      - hadoop_network
    volumes:
      - kibana_data:/usr/share/kibana/data

networks:
  my_custom_network:
    external: true
  hadoop_network:
    external: true
    ipam:
      config:
        - subnet: 172.26.0.0/16

volumes:
  esdata:
    driver: local
  kibana_data:
    driver: local
  #kafka_data:
  #  driver: local
